### ISSUE TITLE
Full practice exam missed

### ISSUE THREAD

**Issue by johnfelipe** [dennislamcv1/MSAI900#1]
![SNAG-0917](https://user-images.githubusercontent.com/428820/168479548-1aeac2ac-2e8a-43b5-afba-8e6c5f8a8f6d.png)

my answers
![SNAG-0918](https://user-images.githubusercontent.com/428820/168479966-bab42013-69e5-4b9a-947f-80225d14b0b4.png)

results
![SNAG-0919](https://user-images.githubusercontent.com/428820/168480035-863f03f2-d0d5-4946-bac7-5e960889a85c.png)

**Comment by johnfelipe** [comment]
@dennislamcv1 help pls

**Comment by dennislamcv1** [comment]
Uploaded mine just now. take note it may be different from yours

**Comment by johnfelipe** [comment]
hi dear i think you upload another, because Full practice exam of this course only have 31 questions, can u review again?

**Comment by dennislamcv1** [comment]
In that case, fyi I passed it in May 2021. Which means Microsoft has changed the questions already for your case.

**Comment by johnfelipe** [comment]
tnks
remember pls my other issues
